#!/bin/bash -e
#
# Cross compile QEMU with mingw toolchain on Linux.
#
# Copyright (c) 2016 Red Hat Inc.
#
# Authors:
#  Fam Zheng <famz@redhat.com>
#
# This work is licensed under the terms of the GNU GPL, version 2
# or (at your option) any later version. See the COPYING file in
# the top-level directory.

. common.rc

requires mingw dtc

CPREFIX=x86_64-w64-mingw32-
TARGET_LIST="x86_64-softmmu,aarch64-softmmu,i386-softmmu"

build_qemu --cross-prefix=$CPREFIX \
          --enable-gnutls \
          --enable-nettle \
          --enable-curl \
          --enable-vnc \
          --enable-bzip2 \
          --with-gtkabi=3.0
make install

ARCHIVE=qemu-mingw64-`date -I`.zip
zip -j /var/tmp/install/${ARCHIVE} $PWD/install/* /usr/x86_64-w64-mingw32/sys-root/mingw/bin/*.dll
echo "DONE: $ARCHIVE"
